---row counts 

SELECT 'DIM_STORE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM RETAIL_INTELLIGENCE.GOLD.DIM_STORE

UNION ALL

SELECT 'FACT_STORE_RISK', COUNT(*)
FROM RETAIL_INTELLIGENCE.GOLD.FACT_STORE_RISK

UNION ALL

SELECT 'STORE_SUMMARY', COUNT(*)
FROM RETAIL_INTELLIGENCE.GOLD.STORE_SUMMARY

UNION ALL

SELECT 'FACT_SALES_MONTHLY', COUNT(*)
FROM RETAIL_INTELLIGENCE.GOLD.FACT_SALES_MONTHLY;

--duplicates 
SELECT
    'DIM_STORE' AS TABLE_NAME,
    COUNT(*) - COUNT(DISTINCT STORE) AS DUPLICATES
FROM RETAIL_INTELLIGENCE.GOLD.DIM_STORE

UNION ALL

SELECT
    'FACT_STORE_RISK',
    COUNT(*) - COUNT(DISTINCT STORE)
FROM RETAIL_INTELLIGENCE.GOLD.FACT_STORE_RISK

UNION ALL

SELECT
    'STORE_SUMMARY',
    COUNT(*) - COUNT(DISTINCT STORE)
FROM RETAIL_INTELLIGENCE.GOLD.STORE_SUMMARY;

SELECT
    COUNT(*) -
    COUNT(DISTINCT STORE || '|' || TO_VARCHAR(MONTH) || '|' || TO_VARCHAR(ISFORECAST))
    AS DUPLICATES
FROM RETAIL_INTELLIGENCE.GOLD.FACT_SALES_MONTHLY;

--risk model validation 
SELECT
    COUNT(*) AS TOTAL_ROWS,
    SUM(
        CASE
            WHEN PROB_HIGH BETWEEN 0 AND 1
             AND PROB_MEDIUM BETWEEN 0 AND 1
             AND PROB_LOW BETWEEN 0 AND 1
             AND ABS(PROB_HIGH + PROB_MEDIUM + PROB_LOW - 1) <= 0.01
            THEN 0
            ELSE 1
        END
    ) AS INVALID_ROWS
FROM RETAIL_INTELLIGENCE.GOLD.FACT_STORE_RISK;

--sales aggregation 
SELECT COUNT(*) AS MISMATCH_COUNT
FROM (
    SELECT
        STORE,
        DATE_TRUNC('MONTH', DATE) AS MONTH,
        SUM(SALES) AS EXPECTED_SALES
    FROM RETAIL_INTELLIGENCE.STAGING.SILVER_TRAIN
    WHERE OPEN = 1
    GROUP BY STORE, DATE_TRUNC('MONTH', DATE)
) S
JOIN RETAIL_INTELLIGENCE.GOLD.FACT_SALES_MONTHLY G
    ON S.STORE = G.STORE
   AND S.MONTH = G.MONTH
WHERE G.ISFORECAST = FALSE
  AND ABS(S.EXPECTED_SALES - G.SALES) > 0.01;